FaceGuard/urls.py
from django.contrib import admin
from django.urls import path, include
from tasks import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name="home"),
    path("signup/", views.signup, name="signup"),
    path("tasks/", views.tasks, name="tasks"),
    path("tasks/completed/", views.tasks_completed, name="tasks_completed"),
    path("tasks/create/", views.create_task, name="create_task"),
    path("tasks/<int:task_id>/", views.task_detail, name="task_detail"),
    path("tasks/<int:task_id>/complete", views.complete_task, name="complete_task"),
    path("tasks/<int:task_id>/delete", views.delete_task, name="delete_task"),
    path("logout/", views.signout, name="logout"),
    path("signin/", views.signin, name="signin"),
    path("areas/", include("areas.urls")),
    path("zonas/", include("areas.zonas_urls")),
    path("puertas/", include("areas.puertas_urls")),
    path('roles/', include('usuarios.roles_urls')),
    path('movimientos/', include('atencion.urls')),
    path('notificaciones/', include('notificaciones.urls')),
    path('usuarios/', include('usuarios.usuarios_urls')),
    path('api/', include('API.api_urls')),
]

areas/urls.py
from django.urls import path
from .views import areas_listar, areas_crear, areas_editar, areas_eliminar

urlpatterns = [
    path('', areas_listar, name='areas_listar'),
    path('crear/', areas_crear, name='areas_crear'),
    path('editar/<int:id>/', areas_editar, name='areas_editar'),
    path('eliminar/<int:id>/', areas_eliminar, name='areas_eliminar'),


    
]

usuarios/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Roles(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField(blank=True)
    activo = models.BooleanField(default=False)

    def __str__(self):
        estado = "activo" if self.activo else "inactivo"
        return f"Rol: {self.nombre} está {estado}"

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=30, blank=True, null=True)
    apellido_p = models.CharField(max_length=30, blank=True, null=True)
    apellido_m = models.CharField(max_length=30, blank=True, null=True)
    fecha_nacimiento = models.DateField(blank=True, null=True)
    sexo = models.CharField(max_length=10, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], blank=True, null=True)
    nss = models.CharField(max_length=15, blank=True, null=True)
    telefono = models.CharField(max_length=15, blank=True, null=True)
    direccion = models.CharField(max_length=255, blank=True, null=True)
    estado = models.CharField(max_length=50, blank=True, null=True)
    ciudad = models.CharField(max_length=50, blank=True, null=True)
    imagen_id = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return f"{self.user.username}'s Profile"

class ProfileRole(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    role = models.ForeignKey(Roles, on_delete=models.CASCADE)
    fecha_vencimiento = models.DateField(null=True, blank=True)

    class Meta:
        unique_together = ('profile', 'role')

    def __str__(self):
        return f"{self.profile.user.username} - {self.role.nombre} (Vence: {self.fecha_vencimiento})"

usuarios/forms.py
from django import forms
from .models import Roles, Profile


class RolesForm(forms.ModelForm):
    class Meta:
        model = Roles
        fields = ['nombre', 'descripcion', 'activo']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Rol'}),
            'descripcion': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Descripción del rol'}),
            'activo': forms.CheckboxInput(attrs={'class': 'form-check-input m-auto mt-1'})
        }

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = [
            'nombre', 'apellido_p', 'apellido_m', 'fecha_nacimiento',
            'sexo', 'nss', 'telefono', 'direccion', 'estado', 'ciudad'
        ]

usuarios/views.py
from datetime import datetime

import requests
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from tensorflow.python.ops.logging_ops import Print

from areas.views import puertas_listar
from atencion.models import Movimiento, MovimientoUsuario, MovimientoPuerta
from .models import Roles, Profile, User, ProfileRole
from areas.models import Puerta, PuertasRoles
from .forms import RolesForm, ProfileForm
from django.contrib.auth.decorators import login_required
from notificaciones.models import Notificacion

from .utils.registro_facial import consultar_imagen_usuario, login_captura_facial


# Views Roles
@login_required
def roles_listar(request):
    roles = Roles.objects.all()
    return render(request, 'roles/roles_listar.html', {'roles': roles})


@login_required
def roles_crear(request):
    if request.method == 'POST':
        form = RolesForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(roles_listar)
    else:
        form = RolesForm()
    return render(request, 'roles/roles_crear.html', {'form': form})


@login_required
def roles_editar(request, id):
    rol = get_object_or_404(Roles, id=id)
    if request.method == 'POST':
        form = RolesForm(request.POST, instance=rol)
        if form.is_valid():
            form.save()  # Actualiza el rol
            return redirect(roles_listar)
    else:
        form = RolesForm(instance=rol)
    return render(request, 'roles/roles_editar.html', {'form': form, 'rol': rol})


@login_required
def roles_eliminar(request, id):
    rol = get_object_or_404(Roles, id=id)
    if request.method == 'POST':
        rol.delete()  # Elimina el rol
        return redirect(roles_listar)
    return render(request, 'roles/roles_eliminar.html', {'rol': rol})

"""
VIEWS Profile (usuarios)
"""

@login_required
def profile_listar(request):
    perfiles = Profile.objects.all()
    perf = Profile.objects.filter(user=request.user).first()
    for perfil in perfiles:
        perfil.roles = perfil.profilerole_set.all()
    if perf:
        perf.roles = list(perf.profilerole_set.all())
    else:
        perf = None
    return render(request, 'usuarios/usuarios_listar.html', {'usuarios': perfiles, "usuari": perf})

"""
@login_required
def profile_crear(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST)
        if form.is_valid():
            perfil = form.save(commit=False)
            perfil.user = request.user
            perfil.save()
            return redirect(profile_listar)
    else:
        form = ProfileForm()
    return render(request, 'usuarios/usuarios_crear.html', {'form': form})
"""

@login_required
def profile_editar(request, id):
    perfil = get_object_or_404(Profile, user_id=id)
    if request.method == 'POST':
        form = ProfileForm(request.POST, instance=perfil)
        if form.is_valid():
            form.save()
            return redirect(profile_listar)
    else:
        form = ProfileForm(instance=perfil)
    return render(request, 'usuarios/usuarios_editar.html', {'form': form, 'perfil': perfil})


@login_required
def usuarios_asignar_roles(request, id):
    perfil = get_object_or_404(Profile, user_id=id)
    roles_asignados = ProfileRole.objects.filter(profile=perfil).values_list('role', flat=True)
    roles = Roles.objects.exclude(id__in=roles_asignados)

    if request.method == 'POST':
        # Procesar los roles seleccionados por el usuario
        selected_roles = request.POST.getlist('roles')
        fecha_vencimiento = request.POST.get('fecha_vencimiento')

        # Si la fecha está vacía, asignar None
        if not fecha_vencimiento:
            fecha_vencimiento = None

        for role_id in selected_roles:
            role = get_object_or_404(Roles, id=role_id)
            ProfileRole.objects.create(profile=perfil, role=role, fecha_vencimiento=fecha_vencimiento)
        return redirect('usuarios_listar')  # Redirige a la lista de usuarios

    return render(request, 'usuarios/usuarios_asignar_roles.html', {'perfil': perfil, 'roles': roles})


@login_required
def eliminar_roles_usuario(request, usuario_id):
    usuario = get_object_or_404(Profile, user_id=usuario_id)

    if request.method == 'POST':
        # Obtener los IDs de los roles seleccionados
        roles_a_eliminar = request.POST.getlist('roles')

        if roles_a_eliminar:
            # Eliminar los roles seleccionados
            ProfileRole.objects.filter(id__in=roles_a_eliminar, profile=usuario).delete()

        return redirect(profile_listar)  # Redirigir después de eliminar

    # Para el GET, mostrar los roles actuales del usuario
    roles_asignados = ProfileRole.objects.filter(profile=usuario)

    return render(request, 'usuarios/eliminar_roles_usuario.html', {
        'usuario': usuario,
        'roles_asignados': roles_asignados
    })

@login_required
def profile_completar(request, id):
    from tasks.views import tasks
    perfil = get_object_or_404(Profile, user_id=id)
    if request.method == 'POST':
        form = ProfileForm(request.POST, instance=perfil)
        if form.is_valid():
            form.save()
            return redirect(tasks)
    else:
        form = ProfileForm(instance=perfil)
    return render(request, 'usuarios/usuarios_completar.html', {'form': form, 'perfil': perfil})

@login_required
def profile_eliminar(request, id):
    perfil = get_object_or_404(User, id=id)
    if request.method == 'POST':
        perfil.delete()
        return redirect(profile_listar)
    return render(request, 'usuarios/usuarios_eliminar.html', {'usuarios': perfil})

def notificar_a_staff(mensaje):
    staff_users = User.objects.filter(is_staff=True)
    for staff_user in staff_users:
        Notificacion.objects.create(
            usuario=staff_user,
            mensaje=mensaje,
            leida=False,
        )

def registrar_movimiento(tipo, usuario, puerta):
    """
    Registra un movimiento en las tablas Movimiento, MovimientoUsuario y MovimientoPuerta.

    :param tipo: Tipo de movimiento ("acceso" o "acceso denegado").
    :param usuario: Instancia del usuario relacionado con el movimiento.
    :param puerta: Instancia de la puerta relacionada con el movimiento.
    """
    # Crear el registro en la tabla principal Movimiento
    movimiento = Movimiento.objects.create(
        tipo=tipo,
        hora=datetime.now().time(),
        fecha=datetime.now().date(),
    )

    # Crear los registros en las tablas intermedias
    MovimientoUsuario.objects.create(movimiento=movimiento, usuario=usuario.user)
    MovimientoPuerta.objects.create(movimiento=movimiento, puerta=puerta)

def verificar_acceso(request, puerta_id):
    # Obtener la puerta
    puerta = get_object_or_404(Puerta, id=puerta_id)

    # Obtener el perfil del usuario actual
    perfil = request.user.profile

    # Obtener los roles del perfil del usuario
    roles_usuario = ProfileRole.objects.filter(profile=perfil).values_list('role', flat=True)

    # Obtener los roles asignados a la puerta
    roles_puerta = PuertasRoles.objects.filter(puerta=puerta).values_list('rol', flat=True)

    # Determinar si hay intersección entre los roles del usuario y los roles de la puerta
    acceso = any(rol in roles_puerta for rol in roles_usuario)

    context = {
        'puerta': puerta,
        'acceso': acceso
    }
    return render(request, 'usuarios/verificar_acceso.html', context)

@login_required
def verificar_rostro_acceso(request, puerta_id):
    print("Metodo de verificar")

    # Obtener los datos de la imagen enviados desde el formulario
    photo_data = request.POST.get("photo")

    if not photo_data:
        print("No se encontró foto en el formulario")
        messages.error(request, "No se encontró foto en el formulario.")
        return redirect(puertas_listar)

    profile = request.user.profile
    puerta = get_object_or_404(Puerta, id=puerta_id)
    perfil = request.user.profile

    if not profile or not profile.imagen_id:
        print("Perfil de usuario inválido o sin imagen registrada")
        messages.error(request, "Perfil de usuario inválido o sin imagen registrada.")
        return redirect(puertas_listar)

    # Consultar la imagen del usuario registrada
    img_profile = profile.imagen_id
    user_face = consultar_imagen_usuario(imagen_id=img_profile)

    if user_face is False:
        print("El usuario no tiene rostro registrado")
        messages.error(request, "El usuario no tiene rostro registrado.")
        return redirect(puertas_listar)

    if user_face is None:
        print("Error al recuperar la imagen del perfil")
        messages.error(request, "Error al recuperar la imagen del perfil.")
        return redirect(puertas_listar)

    # Comparar el rostro registrado con el rostro capturado
    resultado = login_captura_facial(user_face, photo_data)

    if resultado is True:
        # Obtener los roles del perfil del usuario
        roles_usuario = ProfileRole.objects.filter(profile=profile).values_list('role', flat=True)

        # Obtener los roles asignados a la puerta
        roles_puerta = PuertasRoles.objects.filter(puerta=puerta).values_list('rol', flat=True)

        # Determinar si hay intersección entre los roles del usuario y los roles de la puerta
        acceso = any(rol in roles_puerta for rol in roles_usuario)

        if acceso:
            print("acceso es true")
            print(f"Registrar movimiento correcto | perfil {perfil}, puerta {puerta}")
            registrar_movimiento("Acceso", profile, puerta)
            print("Notificacion a staff")
            mensaje = ("Acceso concedido\n"
                       f"Usuario: {perfil.user}\n")
            notificar_a_staff(mensaje)
            print("Notificacion a staff correctamente")
        else:
            print("acceso es false")
            print(f"Registrar movimiento false | perfil {perfil.user_id}, puerta {puerta.pk}")

usuarios/templates/usuarios/eliminar_roles_usuario.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container mt-5">
    <h1 class="display-3">Eliminar Rol de {{ usuario.nombre }}</h1>

    {% if message %}
        <div class="alert alert-info">{{ message }}</div>
    {% endif %}

    <form method="POST">
        {% csrf_token %}
        <table class="table">
            <thead>
                <tr>
                    <th>Seleccionar</th>
                    <th>Rol</th>
                    <th>Fecha de Vencimiento</th>
                </tr>
            </thead>
            <tbody>
                {% for profile_role in roles_asignados %}
                <tr>
                    <td><input type="checkbox" name="roles" value="{{ profile_role.id }}"></td>
                    <td>{{ profile_role.role.nombre }}</td>
                    <td>{{ profile_role.fecha_vencimiento }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <button type="submit" class="btn btn-danger mt-3">Eliminar Roles</button>
    </form>
</div>
{% endblock %}

usuarios/templates/usuarios/usuarios_asignar_roles.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container mt-5">
    <h1 class="display-3">Asignar Rol a {{ perfil.nombre }}</h1>
    
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="roles">Selecciona Roles:</label>
            <select multiple class="form-control" id="roles" name="roles">
                {% for role in roles %}
                <option value="{{ role.id }}">{{ role.nombre }}</option>
                {% endfor %}
            </select>
        </div>

        <!--<div class="form-group mt-3">
            <label for="fecha_vencimiento">Fecha de Vencimiento:</label>
            <input type="date" class="form-control" id="fecha_vencimiento" name="fecha_vencimiento">
        </div>-->

        <button type="submit" class="btn btn-primary mt-3">Asignar Roles</button>
    </form>
</div>
{% endblock %}

usuarios/templates/usuarios/usuarios_completar.html
{% extends 'base.html' %}

{% block content %}
<main class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3 mt-5">
        <form action="{% url 'usuarios_editar' perfil.user_id %}" method="POST" class="card card-body shadow-sm p-4">
          <h1 class="display-5 text-center mb-4">Completar Perfil</h1>
          {% if form.non_field_errors %}
              <div class="alert alert-danger">
                  {{ form.non_field_errors }}
              </div>
          {% endif %}
          {% csrf_token %}

          <!-- Campo Nombre -->
          <div class="mb-3">
              <label for="id_nombre" class="form-label">Nombre</label>
              <input type="text" name="nombre" id="id_nombre" class="form-control">
          </div>

          <!-- Campo Apellido Paterno -->
          <div class="mb-3">
              <label for="id_apellido_p" class="form-label">Apellido Paterno</label>
              <input type="text" name="apellido_p" id="id_apellido_p" class="form-control">
          </div>

          <!-- Campo Apellido Materno -->
          <div class="mb-3">
              <label for="id_apellido_m" class="form-label">Apellido Materno</label>
              <input type="text" name="apellido_m" id="id_apellido_m" class="form-control">
          </div>

          <!-- Campo Fecha de Nacimiento -->
          <div class="mb-3">
              <label for="id_fecha_nacimiento" class="form-label">Fecha de Nacimiento</label>
              <input type="text" name="fecha_nacimiento" id="id_fecha_nacimiento" class="form-control datepicker">
          </div>

          <!-- Campo NSS -->
          <div class="mb-3">
              <label for="id_nss" class="form-label">Número de Seguro Social</label>
              <input type="text" name="nss" id="id_nss" class="form-control">
          </div>

          <!-- Campo Sexo -->
          <div class="mb-3">
              <label for="id_sexo" class="form-label">Sexo</label>
              <select name="sexo" id="id_sexo" class="form-control">
                  <option value="M" {% if form.sexo.value == 'M' %}selected{% endif %}>Masculino</option>
                  <option value="F" {% if form.sexo.value == 'F' %}selected{% endif %}>Femenino</option>
                  <option value="O" {% if form.sexo.value == 'O' %}selected{% endif %}>Otro</option>
              </select>
          </div>

          <!-- Otros campos -->
          <div class="mb-3">
              <label for="id_direccion" class="form-label">Dirección</label>
              <input type="text" name="direccion" id="id_direccion" class="form-control">
          </div>
          <div class="mb-3">
              <label for="id_ciudad" class="form-label">Ciudad</label>
              <input type="text" name="ciudad" id="id_ciudad" class="form-control">
          </div>
          <div class="mb-3">
              <label for="id_estado" class="form-label">Estado</label>
              <input type="text" name="estado" id="id_estado" class="form-control">
          </div>
          <div class="mb-3">
              <label for="id_telefono" class="form-label">Teléfono</label>
              <input type="text" name="telefono" id="id_telefono" class="form-control">
          </div>

          <button type="submit" class="btn btn-primary w-100 mt-3">Guardar</button>
        </form>
    </div>
  </div>
</main>

<!-- Incluye JavaScript para el calendario -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
<script>
  $(document).ready(function () {
    $('.datepicker').datepicker({
      format: 'yyyy-mm-dd',
      autoclose: true,
      todayHighlight: true,
      language: 'es'
    });
  });
</script>
{% endblock %}

usuarios/templates/usuarios/usuarios_editar.html
{% extends 'base.html' %}

{% block content %}
<main class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3 mt-5">
        <form action="{% url 'usuarios_editar' perfil.user_id %}" method="POST" class="card card-body shadow-sm p-4">
          <h1 class="display-5 text-center mb-4">Editar Usuario</h1>
          {% if form.non_field_errors %}
              <div class="alert alert-danger">
                  {{ form.non_field_errors }}
              </div>
          {% endif %}
          {% csrf_token %}

          <!-- Campo Nombre -->
          <div class="mb-3">
              <label for="id_nombre" class="form-label">Nombre</label>
              <input type="text" name="nombre" id="id_nombre" value="{{ form.nombre.value }}" class="form-control">
          </div>

          <!-- Campo Apellido Paterno -->
          <div class="mb-3">
              <label for="id_apellido_p" class="form-label">Apellido Paterno</label>
              <input type="text" name="apellido_p" id="id_apellido_p" value="{{ form.apellido_p.value }}" class="form-control">
          </div>

          <!-- Campo Apellido Materno -->
          <div class="mb-3">
              <label for="id_apellido_m" class="form-label">Apellido Materno</label>
              <input type="text" name="apellido_m" id="id_apellido_m" value="{{ form.apellido_m.value }}" class="form-control">
          </div>

          <!-- Campo Fecha de Nacimiento -->
          <div class="mb-3">
              <label for="id_fecha_nacimiento" class="form-label">Fecha de Nacimiento</label>
              <input type="text" name="fecha_nacimiento" id="id_fecha_nacimiento" value="{{ form.fecha_nacimiento.value }}" class="form-control datepicker">
          </div>

          <!-- Campo NSS -->
          <div class="mb-3">
              <label for="id_nss" class="form-label">Número de Seguro Social</label>
              <input type="text" name="nss" id="id_nss" value="{{ form.nss.value }}" class="form-control">
          </div>

          <!-- Campo Sexo -->
          <div class="mb-3">
              <label for="id_sexo" class="form-label">Sexo</label>
              <select name="sexo" id="id_sexo" class="form-control">
                  <option value="M" {% if form.sexo.value == 'M' %}selected{% endif %}>Masculino</option>
                  <option value="F" {% if form.sexo.value == 'F' %}selected{% endif %}>Femenino</option>
                  <option value="O" {% if form.sexo.value == 'O' %}selected{% endif %}>Otro</option>
              </select>
          </div>

          <!-- Otros campos -->
          <div class="mb-3">
              <label for="id_direccion" class="form-label">Dirección</label>
              <input type="text" name="direccion" id="id_direccion" value="{{ form.direccion.value }}" class="form-control">
          </div>
          <div class="mb-3">
              <label for="id_ciudad" class="form-label">Ciudad</label>
              <input type="text" name="ciudad" id="id_ciudad" value="{{ form.ciudad.value }}" class="form-control">
          </div>
          <div class="mb-3">
              <label for="id_estado" class="form-label">Estado</label>
              <input type="text" name="estado" id="id_estado" value="{{ form.estado.value }}" class="form-control">
          </div>
          <div class="mb-3">
              <label for="id_telefono" class="form-label">Teléfono</label>
              <input type="text" name="telefono" id="id_telefono" value="{{ form.telefono.value }}" class="form-control">
          </div>

          <button type="submit" class="btn btn-primary w-100 mt-3">Guardar</button>
        </form>
    </div>
  </div>
</main>

<!-- Incluye JavaScript para el calendario -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
<script>
  $(document).ready(function () {
    $('.datepicker').datepicker({
      format: 'yyyy-mm-dd',
      autoclose: true,
      todayHighlight: true,
      language: 'es'
    });
  });
</script>
{% endblock %}

usuarios/templates/usuarios/usuarios_listar.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/2.1.8/css/dataTables.bootstrap5.css">
<link rel="stylesheet" href="{% static 'css/data_table.css' %}">

<div class="container mt-5">
    {% if usuari %}
        <h1 class="display-3">Usuario</h1>
    {% endif %}
    {% if request.user.is_staff %}
        <h1 class="display-3">Usuarios</h1>
    {% endif %}
    <table id="usuariosTable" class="table table-striped mt-5">
        <thead style="background-color: #066699 !important; color: white !important;">
            <!--<a href="{% url 'roles_crear' %}" class="btn" style="background-color: #066699; color: white;">
                <i class="bi bi-plus-lg"></i> Añadir
            </a>-->
            <tr>
                <th>Nombre completo</th>
                <th>Dirección</th>
                <th>Ciudad</th>
                <th>Estado</th>
                <th>Teléfono</th>
                <th>Roles</th>
                {% if usuari %}
                    <th>Editar</th>
                {% endif %}
                {% if request.user.is_staff %}
                    <th>Acciones</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% if request.user.is_staff %}
                {% for usuario in usuarios %}
                <tr>
                    <td>{{ usuario.nombre|add:" " }}{{ usuario.apellido_p|add:" " }}{{ usuario.apellido_m }}</td>
                    <td>{{ usuario.direccion }}</td>
                    <td>{{ usuario.ciudad }}</td>
                    <td>{{ usuario.estado }}</td>
                    <td>{{ usuario.telefono }}</td>

                    <td>
                        {% if usuario.roles %}
                            {% for perfil_rol in usuario.roles %}
                                <span class="badge bg-primary">{{ perfil_rol.role.nombre }}</span>
                            {% endfor %}
                        {% else %}
                            <span> - </span>
                        {% endif %}
                    </td>

                    <td>
                        <a href="{% url 'usuarios_editar' usuario.user_id %}" class="btn btn-sm btn-success">
                            <i class="bi bi-pencil-fill"></i>
                        </a>
                        <!--<button type="button" class="btn btn-sm btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal{{ usuario.user_id }}">
                            <i class="bi bi-trash-fill"></i>
                        </button>-->
                        <a href="{% url 'usuarios_asignar_roles' usuario.user_id %}" class="btn btn-sm btn-primary">
                        <i class="bi bi-person-plus-fill"></i>
                        </a>
                        <a href="{% url 'eliminar_roles_usuario' usuario.user_id %}" class="btn btn-sm btn-danger">
                         <i class="bi bi-trash-fill"></i>
                        </a>
                    </td>
                </tr>
                {% include 'modal_eliminar.html' with object_id=usuario.user_id object_name=usuario.nombre delete_url='usuarios_eliminar' %}
                {% endfor %}
            {% endif %}
            {% if usuari %}
                <tr>
                    <td>{{ usuari.nombre|add:" " }}{{ usuari.apellido_p|add:" " }}{{ usuari.apellido_m }}</td>
                    <td>{{ usuari.direccion }}</td>
                    <td>{{ usuari.ciudad }}</td>
                    <td>{{ usuari.estado }}</td>
                    <td>{{ usuari.telefono }}</td>

                    <td>
                        {% if usuari.roles %}
                            {% for perfil_rol in usuari.roles %}
                                <span class="badge bg-primary">{{ perfil_rol.role.nombre }}</span>
                            {% endfor %}
                        {% else %}
                            <span> - </span>
                        {% endif %}
                    </td>

                    <td>
                        <a href="{% url 'usuarios_editar' usuari.user_id %}" class="btn btn-sm btn-success">
                            <i class="bi bi-pencil-fill"></i>
                        </a>
                    </td>
                </tr>
                {% include 'modal_eliminar.html' with object_id=usuari.user_id object_name=usuari.nombre delete_url='usuarios_eliminar'%}
            {% endif %}
        </tbody>
    </table>
</div>

<script src="https://code.jquery.com/jquery-3.7.1.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.datatables.net/2.1.8/js/dataTables.js"></script>
<script src="https://cdn.datatables.net/2.1.8/js/dataTables.bootstrap5.js"></script>
<script src="{% static 'js/data_table.js' %}"></script>

<!-- DataTables Initialization -->
<script>
    $(document).ready(function() {
        $('#usuariosTable').DataTable({
            "language": {
            }
        });
    });
</script>
{% endblock %}

usuarios/templates/usuarios/verificar_acceso.html
{% extends "base.html" %}

{% block content %}
<main class="container">
  <h1 class="mt-5">Verificación de Acceso</h1>
  
  {% if acceso %}
    <div class="alert alert-success">¡Tienes acceso a esta puerta!</div>
  {% else %}
    <div class="alert alert-danger">No tienes acceso a esta puerta.</div>
  {% endif %}
  
  <a href="{% url 'puertas_listar' %}" class="btn btn-primary mt-3">Volver</a>
</main>
{% endblock %}